name: NSign

on:
  # schedule:
  #   - cron: '58 8 * * *'
  workflow_dispatch:

jobs:
  sign:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout codes
        uses: actions/checkout@v4
      - name: Update system and install zsh
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get install zsh -y
          
      - name: Init Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
          
      - name: Start
        env:
            ELANTRAN_AUTH: ${{ secrets.ELANTRAN_AUTH }}
            PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
        run: |
          pip3 install requests pytz
          python3 elantran_checkin.py
